services:
  - type: web
    name: chatbit-server
    env: node
    plan: free
    rootDir: apps/server
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: BETTER_AUTH_URL
        value: https://chatbit-server.onrender.com
      - key: CORS_ORIGIN
        value: https://chatbit.nawin.xyz
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false 